#!/bin/bash

cp -R ./ReportHelper /applications/ReportHelper
if ! command -v python3 &> /dev/null
then
    echo Python3 not found
    echo Python3 is a required dependancy, do you wish to install?
    read to_install
    if [ “$to_install” = “yes” ]
    then    
        echo Installing
        cp -R ./IDLE ./applications/python 3.9
        echo Python 3.9 installed!
    fi
else
    echo Python3 found
fi